In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split, RandomizedSearchCV, KFold
from sklearn.preprocessing import OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, ConfusionMatrixDisplay
from scipy.stats import randint as sp_randint
from scipy.stats import uniform
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_csv('Pokemon.csv')

In [5]:
df.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

In [8]:
encoder = OneHotEncoder(sparse_output=False)
onehot = encoder.fit_transform(df[['Type 1', 'Type 2']])

In [9]:
# Visualizza il risultato
print(onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [11]:
column_names = encoder.get_feature_names_out(['Type 1', 'Type 2'])
encoded_df = pd.DataFrame(onehot, columns=column_names)
result = pd.concat([df, encoded_df], axis=1)

In [16]:
result.drop(["Type 1", "Type 2"], axis=1)

#                   Name  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0      1              Bulbasaur    318  45      49       49       65       65   
1      2                Ivysaur    405  60      62       63       80       80   
2      3               Venusaur    525  80      82       83      100      100   
3      3  VenusaurMega Venusaur    625  80     100      123      122      120   
4      4             Charmander    309  39      52       43       60       50   
..   ...                    ...    ...  ..     ...      ...      ...      ...   
795  719                Diancie    600  50     100      150      100      150   
796  719    DiancieMega Diancie    700  50     160      110      160      110   
797  720    HoopaHoopa Confined    600  80     110       60      150      130   
798  720     HoopaHoopa Unbound    680  80     160       60      170      130   
799  721              Volcanion    600  80     110      120      130       90   

     Speed  Generation  ...  Type 2_Grass  Type 2_Ground  Type 2_Ice  \
0       45           1  ...           0.0            0.0         0.0   
1       60           1  ...           0.0            0.0         0.0   
2       80           1  ...           0.0            0.0         0.0   
3       80           1  ...           0.0            0.0         0.0   
4       65           1  ...           0.0            0.0         0.0   
..     ...         ...  ...           ...            ...         ...   
795     50           6  ...           0.0            0.0         0.0   
796    110           6  ...           0.0            0.0         0.0   
797     70           6  ...           0.0            0.0         0.0   
798     80           6  ...           0.0            0.0         0.0   
799     70           6  ...           0.0            0.0         0.0   

     Type 2_Normal  Type 2_Poison  Type 2_Psychic  Type 2_Rock  Type 2_Steel  \
0              0.0            1.0             0.0          0.0           0.0   
1              0.0            1.0             0.0          0.0           0.0   
2              0.0            1.0             0.0          0.0           0.0   
3              0.0            1.0             0.0          0.0           0.0   
4              0.0            0.0             0.0          0.0           0.0   
..             ...            ...             ...          ...           ...   
795            0.0            0.0             0.0          0.0           0.0   
796            0.0            0.0             0.0          0.0           0.0   
797            0.0            0.0             0.0          0.0           0.0   
798            0.0            0.0             0.0          0.0           0.0   
799            0.0            0.0             0.0          0.0           0.0   

     Type 2_Water  Type 2_nan  
0             0.0         0.0  
1             0.0         0.0  
2             0.0         0.0  
3             0.0         0.0  
4             0.0         1.0  
..            ...         ...  
795           0.0         0.0  
796           0.0         0.0  
797           0.0         0.0  
798           0.0         0.0  
799           1.0         0.0  

[800 rows x 48 columns]